changesDir: .changes
unreleasedDir: unreleased
headerPath: header.tpl.md
versionHeaderPath: ""
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## dbt-spark {{.Version}} - {{.Time.Format "January 02, 2006"}}'
kindFormat: '### {{.Kind}}'
changeFormat: |-
  {{- $IssueList := list }}
  {{- $changes := splitList " " $.Custom.Issue }}
  {{- range $issueNbr := $changes }}
    {{- $changeLink := "[#nbr](https://github.com/dbt-labs/dbt-spark/issues/nbr)" | replace "nbr" $issueNbr }}
    {{- $IssueList = append $IssueList $changeLink  }}
  {{- end -}}
  - {{.Body}} ({{ range $index, $element := $IssueList }}{{if $index}}, {{end}}{{$element}}{{end}})

kinds:
- label: Breaking Changes
- label: Features
- label: Fixes
- label: Under the Hood
- label: Dependencies
  changeFormat: |-
    {{- $PRList := list }}
    {{- $changes := splitList " " $.Custom.PR }}
    {{- range $pullrequest := $changes }}
      {{- $changeLink := "[#nbr](https://github.com/dbt-labs/dbt-spark/pull/nbr)" | replace "nbr" $pullrequest }}
      {{- $PRList = append $PRList $changeLink  }}
    {{- end -}}
    - {{.Body}} ({{ range $index, $element := $PRList }}{{if $index}}, {{end}}{{$element}}{{end}})
  skipGlobalChoices: true
  additionalChoices:
    - key: Author
      label: GitHub Username(s) (separated by a single space if multiple)
      type: string
      minLength: 3
    - key: PR
      label: GitHub Pull Request Number (separated by a single space if multiple)
      type: string
      minLength: 1
- label: Security
  changeFormat: |-
    {{- $PRList := list }}
    {{- $changes := splitList " " $.Custom.PR }}
    {{- range $pullrequest := $changes }}
      {{- $changeLink := "[#nbr](https://github.com/dbt-labs/dbt-spark/pull/nbr)" | replace "nbr" $pullrequest }}
      {{- $PRList = append $PRList $changeLink  }}
    {{- end -}}
    - {{.Body}} ({{ range $index, $element := $PRList }}{{if $index}}, {{end}}{{$element}}{{end}})
  skipGlobalChoices: true
  additionalChoices:
    - key: Author
      label: GitHub Username(s) (separated by a single space if multiple)
      type: string
      minLength: 3
    - key: PR
      label: GitHub Pull Request Number (separated by a single space if multiple)
      type: string
      minLength: 1

newlines:
  afterChangelogHeader: 1
  afterKind: 1
  afterChangelogVersion: 1
  beforeKind: 1
  endOfVersion: 1

custom:
- key: Author
  label: GitHub Username(s) (separated by a single space if multiple)
  type: string
  minLength: 3
- key: Issue
  label: GitHub Issue Number (separated by a single space if multiple)
  type: string
  minLength: 1

footerFormat: |
  {{- $contributorDict := dict }}
  {{- /* any names added to this list should be all lowercase for later matching purposes */}}
  {{- $core_team := list "michelleark" "peterallenwebb" "emmyoop" "nathaniel-may" "gshank" "leahwicz" "chenyulinx" "stu-k" "iknox-fa" "versusfacit" "mcknight-42" "jtcohen6" "aranke" "dependabot[bot]" "snyk-bot" "colin-rogers-dbt" }}
  {{- range $change := .Changes }}
    {{- $authorList := splitList " " $change.Custom.Author }}
    {{- /* loop through all authors for a single changelog */}}
    {{- range $author := $authorList }}
      {{- $authorLower := lower $author }}
      {{- /* we only want to include non-core team contributors */}}
      {{- if not (has $authorLower $core_team)}}
        {{- $changeList := splitList " " $change.Custom.Author }}
          {{- $IssueList := list }}
          {{- $changeLink := $change.Kind }}
          {{- if or (eq $change.Kind "Dependencies") (eq $change.Kind "Security") }}
            {{- $changes := splitList " " $change.Custom.PR }}
            {{- range $issueNbr := $changes }}
              {{- $changeLink := "[#nbr](https://github.com/dbt-labs/dbt-spark/pull/nbr)" | replace "nbr" $issueNbr }}
              {{- $IssueList = append $IssueList $changeLink  }}
            {{- end -}}
          {{- else }}
            {{- $changes := splitList " " $change.Custom.Issue }}
            {{- range $issueNbr := $changes }}
              {{- $changeLink := "[#nbr](https://github.com/dbt-labs/dbt-spark/issues/nbr)" | replace "nbr" $issueNbr }}
              {{- $IssueList = append $IssueList $changeLink  }}
            {{- end -}}
          {{- end }}
          {{- /* check if this contributor has other changes associated with them already */}}
          {{- if hasKey $contributorDict $author }}
            {{- $contributionList := get $contributorDict $author }}
            {{- $contributionList = concat $contributionList $IssueList  }}
            {{- $contributorDict := set $contributorDict $author $contributionList }}
          {{- else }}
            {{- $contributionList := $IssueList }}
            {{- $contributorDict := set $contributorDict $author $contributionList }}
          {{- end }}
        {{- end}}
    {{- end}}
  {{- end }}
  {{- /* no indentation here for formatting so the final markdown doesn't have unneeded indentations */}}
  {{- if $contributorDict}}
  ### Contributors
  {{- range $k,$v := $contributorDict }}
  - [@{{$k}}](https://github.com/{{$k}}) ({{ range $index, $element := $v }}{{if $index}}, {{end}}{{$element}}{{end}})
  {{- end }}
  {{- end }}
