# **what?**
# Open an issue in docs.getdbt.com when a PR is labeled `user docs`

# **why?**
# To reduce barriers for keeping docs up to date

# **when?**
# When a PR is labeled `user docs` and is merged.  Runs on pull_request_target to run off the workflow already merged,
# not the workflow that existed on the PR branch.  This allows old PRs to get comments.


name: Open issues in docs.getdbt.com repo when a PR is labeled
run-name: "Open an issue in docs.getdbt.com for PR #${{ github.event.pull_request.number }}"

on:
  pull_request_target:
    types: [labeled, closed]

defaults:
  run:
    shell: bash

permissions:
    issues: write # opens new issues
    pull-requests: write # comments on PRs


jobs:
  open_issues:
    # we only want to run this when the PR has been merged or the label in the labeled event is `user docs`.  Otherwise it runs the
    # risk of duplicaton of issues being created due to merge and label both triggering this workflow to run and neither having
    # generating the comment before the other runs.  This lives here instead of the shared workflow because this is where we
    # decide if it should run or not.
    if: |
      (github.event.pull_request.merged == true) &&
      ((github.event.action == 'closed' && contains( github.event.pull_request.labels.*.name, 'user docs')) ||
      (github.event.action == 'labeled' && github.event.label.name == 'user docs'))
    uses: dbt-labs/actions/.github/workflows/open-issue-in-repo.yml@main
    with:
        issue_repository: "dbt-labs/docs.getdbt.com"
        issue_title: "Docs Changes Needed from ${{ github.event.repository.name }} PR #${{ github.event.pull_request.number }}"
        issue_body: "At a minimum, update body to include a link to the page on docs.getdbt.com requiring updates and what part(s) of the page you would like to see updated."
    secrets: inherit
