# **what?**
# Open an issue in docs.getdbt.com when an issue is labeled `user docs` and closed as completed

# **why?**
# To reduce barriers for keeping docs up to date

# **when?**
# When an issue is labeled `user docs` and is closed as completed.  Can be labeled before or after the issue is closed.


name: Open issues in docs.getdbt.com repo when an issue is labeled
run-name: "Open an issue in docs.getdbt.com for issue #${{ github.event.issue.number }}"

on:
  issues:
    types: [labeled, closed]

defaults:
  run:
    shell: bash

permissions:
    issues: write # comments on issues

jobs:
  open_issues:
    # we only want to run this when the issue is closed as completed and the label `user docs` has been assigned.
    # If this logic does not exist in this workflow, it runs the
    # risk of duplicaton of issues being created due to merge and label both triggering this workflow to run and neither having
    # generating the comment before the other runs.  This lives here instead of the shared workflow because this is where we
    # decide if it should run or not.
    if: |
      (github.event.issue.state == 'closed' && github.event.issue.state_reason == 'completed') && (
      (github.event.action == 'closed' && contains(github.event.issue.labels.*.name, 'user docs')) ||
      (github.event.action == 'labeled' && github.event.label.name == 'user docs'))
    uses: dbt-labs/actions/.github/workflows/open-issue-in-repo.yml@main
    with:
        issue_repository: "dbt-labs/docs.getdbt.com"
        issue_title: "Docs Changes Needed from ${{ github.event.repository.name }} Issue #${{ github.event.issue.number }}"
        issue_body: "At a minimum, update body to include a link to the page on docs.getdbt.com requiring updates and what part(s) of the page you would like to see updated."
    secrets: inherit
